# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 020e15c25b31fdcb797125b691f4cd02e606e05e66bc418324a818fe427207764581a65b91cfed5b37d0018f0336f2460009d29ea0af59669027de97b1ece3e1

test:
  secret_key_base: 9af2332fdfbcee94c30aaa8121cb01f36b66a83db47123c386edc29f002e80c7c1dce5b5f0541740445afe25eeb595478beb07d21eff948f3ae310fa2fe05e2b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
